ID-B-4.1
dsladkov/Pet4U pull request #5
Opened 2024-09-28 18:32 UTC by dsladkov

ID-B-4.1

2024-09-28 20:10 UTC, YADARAN1 requested changes

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/Pet.cs
> +    public Volunteer? Volunteer { get; set; }
Это тут не нужно

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/Pet.cs
> +    public Pet(PetId id) : base(id){}
Это должен быть приватный конструктор

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/Pet.cs
> +
все свойства приравнять друг к другу

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/Volunteer.cs
> +    public Volunteer(VolunteerId id, FullName fullName, string email, string description, int experience, string phone) : base(id)
Один параметр на одной строке

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/PetId.cs
> +  public static PetId Create(Guid id) => new (id);
GetNew и Create это одно и то же

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/VolunteerId.cs
> +  public VolunteerId GetEmpty() => new (Guid.Empty);
.

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Domain/Modules/VolunteerId.cs
> +  public static VolunteerId Create(Guid id) => new (id);
.

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Infrastructure/ApplicationDbContext.cs
> +        .UseLoggerFactory( CreatedLoggerFactory() );
Добавь EnableSensetiveDataLogging

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Infrastructure/Configurations/VolunteerConfiguration.cs
> +            .IsRequired(false);
IsRequired(false) не нужно указывать

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Infrastructure/Configurations/VolunteerConfiguration.cs
> +                   .IsRequired(false);
Тут тоже

2024-09-28 20:10 UTC, YADARAN1 commented on src/Pet4U.Infrastructure/Pet4U.Infrastructure.csproj
> +    <ProjectReference Include="..\Pet4U.Domain\Pet4U.Domain.csproj" />
Тут не должно быть ссылки на слой с Domain'ом

2024-09-28 20:19 UTC, dsladkov commented on src/Pet4U.Infrastructure/Pet4U.Infrastructure.csproj
> +    <ProjectReference Include="..\Pet4U.Domain\Pet4U.Domain.csproj" />
В Domain находятся модели. В Infrastructure использую билдер сущностей. Без ссылки не получится или Domain  будет в Infrastructure

2024-09-28 20:19 UTC, dsladkov commented on src/Pet4U.Infrastructure/Pet4U.Infrastructure.csproj
> +    <ProjectReference Include="..\Pet4U.Domain\Pet4U.Domain.csproj" />
В смысле модели

2024-09-29 13:28 UTC, dsladkov commented on src/Pet4U.Domain/Modules/PetId.cs
> +  public static PetId Create(Guid id) => new (id);
Не совсем. метод Create нужен только для ef core

2024-09-29 13:30 UTC, dsladkov commented on src/Pet4U.Domain/Modules/PetId.cs
> +  public static PetId Create(Guid id) => new (id);
Понял. Ок

2024-09-29 13:31 UTC, dsladkov commented on src/Pet4U.Domain/Modules/VolunteerId.cs
> +  public static VolunteerId Create(Guid id) => new (id);
Ok

2024-09-29 13:32 UTC, dsladkov commented on src/Pet4U.Infrastructure/ApplicationDbContext.cs
> +        .UseLoggerFactory( CreatedLoggerFactory() );
Ok

2024-09-29 14:48 UTC, dsladkov commented on src/Pet4U.Domain/Modules/Pet.cs
> +
Ok

2024-09-29 14:48 UTC, dsladkov commented on src/Pet4U.Domain/Modules/Pet.cs
> +    public Pet(PetId id) : base(id){}
Ok

2024-09-29 14:54 UTC, dsladkov commented on src/Pet4U.Domain/Modules/Volunteer.cs
> +    public Volunteer(VolunteerId id, FullName fullName, string email, string description, int experience, string phone) : base(id)
Ok

2024-09-29 14:57 UTC, dsladkov commented on src/Pet4U.Infrastructure/Configurations/VolunteerConfiguration.cs
> +            .IsRequired(false);
Ok

2024-09-29 14:57 UTC, dsladkov commented on src/Pet4U.Infrastructure/Configurations/VolunteerConfiguration.cs
> +                   .IsRequired(false);
Ok

2024-09-29 15:28 UTC, dsladkov commented on src/Pet4U.Domain/Modules/Pet.cs
> +    public Volunteer? Volunteer { get; set; }
Ok

2024-09-29 15:33 UTC, dsladkov commented
У меня в Domain  модели, поэтому  есть реф на проект в инфра
<ProjectReference Include="..\Pet4U.Domain\Pet4U.Domain.csproj" />

2024-09-29 16:28 UTC, KirillSachkov commented on src/Pet4U.Infrastructure/Pet4U.Infrastructure.csproj
> +    <ProjectReference Include="..\Pet4U.Domain\Pet4U.Domain.csproj" />
Если ты ссылаешься на Application, то ты можешь использовать проекты, на которые ссылается Application. Пожтому не нужно ссылаться на domain напрямую

2024-09-29 16:28 UTC, KirillSachkov requested changes
Если ты ссылаешься на Application, то ты можешь использовать проекты, на которые ссылается Application. Пожтому не нужно ссылаться на domain напрямую

2024-09-29 16:34 UTC, dsladkov commented
реф на Application - ошибка

2024-09-29 17:00 UTC, dsladkov commented
Разобрался
Убрал реф на Domain

2024-09-29 17:04 UTC, KirillSachkov approved these changes

2024-09-29 17:08 UTC, merged